### PR TITLE
Improved dependency injection & minor type_traits fix

### PR DESCRIPTION
**Pull request by AnthonyVH**
The main reason for this pull request is fixing issue #139. When e.g. a guard function requires a dependency by const reference, this will now be properly injected, even if the dependency was not explicitly injected as const to the FSM's constructor.

More specifically, injection happens in `aux::pool` (aux_/utility.hpp) as follows:
1. Inject the required type `Ts` from `pool_type<Ts>` it is base class of `pool<TArgs...>`. _(This is what used to be there.)_
2. If the previous step did not work, check if `Ts` is `const` (ignoring references). If so, and if `pool_type<remove_const_t<Ts>>` (with extra fix for reference if `Ts` is a reference) is a base class of `pool<TArgs...>`, then inject a const reference to that.
3. Fail injection.

In the course of adding this code, I noticed that `aux::remove_reference_t` behaved different from `std::remove_reference_t`, in that it also removed const from lvalue reference types (but not from value or rvalue reference types). Fixing this broke the code that is responsible for not trying to inject dependencies to events. This was easily fixed by adding a `remove_const_t` in the appropriate spot in `front::ignore::non_events::type`.

Modifying `aux::remove_reference_t` broke one the `remove_reference_types` test (test/ut/type_traits.cpp). The test was modified to match the results expected from `std::remove_reference_t`.

The resulting code was build & tested with clang 6.0.0-svn321133-1\~exp1 and g++ 7.2.0-1ubuntu1\~16.04. Clang gives errors due to unused lambda captures in test/ut/ft/sizeof.cpp (lines 53, 58, 63). Everything else passes for both compilers.

### CODE REVIEW

**Comment by krzysztof-jusiak** [comment]
Thanks, @AnthonyVH. Good stuff. Would you be able to add a feature test for the functionality, please so that it won't be removed or messed up in the future?

**Comment by AnthonyVH** [comment]
Sure, that should be rather trivial (simply have a guard and action which take a dependency by const and non-const reference respectively). I hope to be able to create something by the end of the weekend.

**Comment by krzysztof-jusiak** [comment]
Thank you :+1:

**Comment by AnthonyVH** [comment]
Sure, that should be rather trivial (simply have a guard and action which take a dependency by const and non-const reference respectively). I hope to be able to create something by the end of the week.

**Comment by AnthonyVH** [comment]
As requested a simple test has been added.

**Pull request merged**
